import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/Providers";
import NavBar from "./components/NavBar";
import "primereact/resources/themes/lara-dark-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import { I18nProvider } from "./components/i18n-providers";



export const metadata: Metadata = {
  title: "HelpDeskPro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Providers>
          <I18nProvider>
            <NavBar />
            {children}
          </I18nProvider>
        </Providers>
      </body>
    </html>
  );
}
